server:
  port: 8091
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fxcal
    username: arbor
    password: arbor123
    tomcat:
      max-wait: 20000
      max-active: 50
      max-idle: 20
      min-idle: 15
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        ddl-auto: create
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#        id:
#          new_generator_mappings: false
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
    au: 
      com:
        nab:
          fx:
            challenge: DEBUG              
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE
